### ISSUE TITLE
 I found a bug

### ISSUE THREAD

**Issue by bau720123** [phonostar/PhoneGap-SoftKeyboard#3]
Android 4.03 and 4.11

when I call your method

```
SoftKeyboard.isShowing(function(){ alert('success'); }, function(){ alert('fail'); })
```

it will alert 'success'

but when I only call your method

```
SoftKeyboard.show()
```

and the keyboard will show about Half a second (In fact, a shorter time)
and disappear by itself

**Comment by kaansoral** [comment]
+1 - used to work at the earlier versions of the cordova though ...

**Comment by tobias-b** [comment]
Our README example was wrong. We have updated the README but have also discontinued the development of this plugin. Please fork if there still is a issue and you want to fix it.
