### ISSUE TITLE
Which version of Android does the plugin support?

### ISSUE THREAD

**Issue by jack87918** [phonostar/PhoneGap-SoftKeyboard#6]
Hi,
This plugin does not work in Android 4.4+ but it works well in the devices which are <Android 4.4 such as 4.1,4.2,4.3.
Any suggestion?
Thanks.

Best Regards,
Jack

**Comment by eswarreddy43** [comment]
Hi,
I am also facing the same problem. So how can I auto use this in 4.4 and >4.4 versions.
Suggest me.

**Comment by tobias-b** [comment]
We have only tested the plugin until Android version 4.1.2. Our use case was to handle hardware search button action. If this does not work for you feel free to fork the plugin because we discontinued development.

**Comment by jack87918** [comment]
thanks a lot.

**Comment by jack87918** [comment]
thanks a lot.

**Comment by jack87918** [comment]
thanks a lot.
